import MuiThemeProvider from './theme-provider';
import './globals.css'; // 引入全局样式
import React from 'react';
import BreathBg from './BreathBg'; // 新增：引入客户端动画组件

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ position: 'relative', minHeight: '100vh', '--breath-speed': '8s' } as any}>
        {/* 多弥散圆动态背景层，4个圆，最后一个跟随鼠标 */}
        <BreathBg />
        {/* 主内容 */}
        <div style={{ position: 'relative', zIndex: 1 }}>
          <MuiThemeProvider>
            {children}
          </MuiThemeProvider>
        </div>
      </body>
    </html>
  )
}
